version: '3.9'

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
      - ./entrypoint.sh:/entrypoint.sh
    entrypoint: [ "sh", "/entrypoint.sh" ]
    environment:
      - OLLAMA_MODELS=mistral

  app:
    build:
      context: .
    container_name: intelligent-bot
    volumes:
      - ./chroma_db:/app/chroma_db
    depends_on:
      - ollama
    environment:
      - PYTHONUNBUFFERED=1
      - OLLAMA_URL=http://ollama:11434
    tty: true
    stdin_open: true

volumes:
  ollama_data:
